// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Producto struct {
	ID          int32          `json:"id"`
	Nombre      string         `json:"nombre"`
	Categoria   string         `json:"categoria"`
	Precio      string         `json:"precio"`
	Descripcion sql.NullString `json:"descripcion"`
}
