// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createProducto = `-- name: CreateProducto :one
INSERT INTO producto (nombre, categoria, precio, descripcion)
VALUES ($1, $2, $3, $4)
RETURNING id, nombre, categoria, precio, descripcion
`

type CreateProductoParams struct {
	Nombre      string         `json:"nombre"`
	Categoria   string         `json:"categoria"`
	Precio      string         `json:"precio"`
	Descripcion sql.NullString `json:"descripcion"`
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, createProducto,
		arg.Nombre,
		arg.Categoria,
		arg.Precio,
		arg.Descripcion,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Categoria,
		&i.Precio,
		&i.Descripcion,
	)
	return i, err
}

const deleteProducto = `-- name: DeleteProducto :exec
DELETE FROM producto WHERE id = $1
`

func (q *Queries) DeleteProducto(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProducto, id)
	return err
}

const getProducto = `-- name: GetProducto :one
SELECT id, nombre, categoria, precio, descripcion FROM producto WHERE id = $1
`

func (q *Queries) GetProducto(ctx context.Context, id int32) (Producto, error) {
	row := q.db.QueryRowContext(ctx, getProducto, id)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Categoria,
		&i.Precio,
		&i.Descripcion,
	)
	return i, err
}

const listProductos = `-- name: ListProductos :many
SELECT id, nombre, categoria, precio, descripcion FROM producto ORDER BY categoria, nombre
`

func (q *Queries) ListProductos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.QueryContext(ctx, listProductos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Producto
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Categoria,
			&i.Precio,
			&i.Descripcion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProducto = `-- name: UpdateProducto :one
UPDATE producto
SET nombre = $2, categoria = $3, precio = $4, descripcion = $5
WHERE id = $1
RETURNING id, nombre, categoria, precio, descripcion
`

type UpdateProductoParams struct {
	ID          int32          `json:"id"`
	Nombre      string         `json:"nombre"`
	Categoria   string         `json:"categoria"`
	Precio      string         `json:"precio"`
	Descripcion sql.NullString `json:"descripcion"`
}

func (q *Queries) UpdateProducto(ctx context.Context, arg UpdateProductoParams) (Producto, error) {
	row := q.db.QueryRowContext(ctx, updateProducto,
		arg.ID,
		arg.Nombre,
		arg.Categoria,
		arg.Precio,
		arg.Descripcion,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Categoria,
		&i.Precio,
		&i.Descripcion,
	)
	return i, err
}
